function [yeq, x, Teq] = VLE(fuel)
close all

% % VLE calculates the the saturation curve for a binary system comprised
% of a fuel and nitrogen at 3, 4.5, and 6 MPa. fuel is a string with the fuel's name. Possible
% fuels are 'butanol', 'dodecane', and 'hexadecane'.




if ~(exist(fuel)==2)
%% pressures and vapor phase fuel mixture fractions
p = [30 45 60].*100000;
x = linspace(.01, .99, 200);

%% provide substance-specific coefficients necessary to solve objective function
[Tcf, pcf, wf] = propData(fuel);    
[TcN2, pcN2, wN2] = propData('nitrogen');

switch fuel
        %% binary interaction parameter from Liu & Reitz, IJMF 2014
        case 'dodecane'
            k = .2082; 
        case 'hexadecane'
            k = .1816;
        %% from 
        case 'butanol'
            k = 0.059;
end

%% Calculate VLE
for j = 1:length(p)

    %% set initial guesses
    yguess = 1; %% second phase mixture fraction 
    Tguess = 500; %% 2-phase equilibrium temperature 

     for m = 1:length(x) 

        %% find equilibrium temperature and mixture fraction using root-finding
         handle = @(r) g(TcN2,Tcf,r(1),k,pcN2,pcf,p(j),wN2,wf,x(m),r(2), fuel);
         [out] = fsolve(handle, [Tguess; yguess]);

         % Save outputs as new initial guesses
         yguess = out(2);
         Tguess = out(1);

         % Save outputs
         yeq(j, m) = out(2);
         Teq(j, m) = out(1);

         %% if at critical point, go to next pressure
         if abs(x(m)-out(2))<=1/200
             break
         end
    end
end
    

save(fuel)
else 
    load(fuel)
end
%% plot saturation curves
plotVLE(fuel, yeq, x, Teq)

end

function g = g(TcN2,Tcf,Ti,k,pcN2,pcf,pj,wN2,wf,xi,yi, fuel)
%G
%    G = G(TCN2,TCF,TI,K,PCN2,PCF,PJ,VL,VV,WN2,WF,XI,YI)
[vv, vl] = findrealV(TcN2,Tcf,Ti,k,pcN2,pcf,pj,wN2,wf,xi,yi, fuel);
%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    28-Aug-2015 12:59:31

t2 = 1.0./Ti;
t3 = 1.0./pcf;
t4 = 1.0./pcN2;
t5 = xi-1.0;
t6 = vv.*2.0;
t23 = 1.0./TcN2;
t24 = Ti.*t23;
t25 = sqrt(t24);
t26 = t25-1.0;
t27 = wN2.*1.54226;
t28 = wN2.^2;
t29 = t28.*2.6993e-1;
t30 = t27-t29+3.7464e-1;
t31 = t26.*t30;
t7 = t31-1.0;
t11 = 1.0./Tcf;
t12 = Ti.*t11;
t13 = sqrt(t12);
t14 = t13-1.0;
t15 = wf.*1.54226;
t16 = wf.^2;
t17 = t16.*2.6993e-1;
t18 = t15-t17+3.7464e-1;
t19 = t14.*t18;
t8 = t19-1.0;
t9 = Tcf.^2;
t10 = conj(xi);
t20 = t8.^2;
t21 = k-1.0;
t22 = TcN2.^2;
t32 = t7.^2;
t33 = t3.*t4.*t9.*t20.*t22.*t32.*9.991370508584246e2;
t34 = sqrt(t33);
t35 = TcN2.*t4.*t5.*6.4686515138e-1;
t44 = Tcf.*t3.*xi.*6.4686515138e-1;
t36 = t35-t44;
t37 = 1.0./t36;
t38 = t5.*t21.*t34.*xi.*2.0;
t39 = xi.^2;
t40 = t3.*t9.*t20.*t39.*3.16091292328407e1;
t41 = t5.^2;
t42 = t4.*t22.*t32.*t41.*3.16091292328407e1;
t43 = t38+t40+t42;
t45 = Ti.*8.3144621;
t46 = yi-1.0;
t47 = sqrt(2.0);
t48 = vl.*2.0;
t49 = conj(yi);
t50 = TcN2.*t4.*t46.*6.4686515138e-1;
t75 = Tcf.*t3.*yi.*6.4686515138e-1;
t51 = t50-t75;
t52 = 1.0./t51;
t53 = t21.*t34.*t46.*yi.*2.0;
t54 = yi.^2;
t55 = t3.*t9.*t20.*t54.*3.16091292328407e1;
t56 = t46.^2;
t57 = t4.*t22.*t32.*t56.*3.16091292328407e1;
t58 = t53+t55+t57;
t59 = t35-t44+vv;
t60 = pj.*t2.*t59.*1.202723625380408e-1;
t61 = log(t60);
t62 = t45-pj.*vv;
t63 = TcN2.*t4.*t5.*5.378335784959773;
t64 = t63-Tcf.*t3.*xi.*5.378335784959773;
t65 = 1.0./t64;
t66 = TcN2.*t4.*t5.*5.358806374562425e-1;
t67 = t6+t66-Tcf.*t3.*xi.*5.358806374562425e-1;
t68 = 1.0./t67;
t69 = Tcf.*t3.*xi.*3.123341242976242;
t70 = t6+t69-TcN2.*t4.*t5.*3.123341242976242;
t71 = t68.*t70;
t72 = log(t71);
t73 = t10-1.0;
t74 = 1.0./t43;
t76 = t45-pj.*vl;
t77 = TcN2.*t4.*t46.*5.378335784959773;
t78 = t77-Tcf.*t3.*yi.*5.378335784959773;
t79 = 1.0./t78;
t80 = TcN2.*t4.*t46.*5.358806374562425e-1;
t81 = t48+t80-Tcf.*t3.*yi.*5.358806374562425e-1;
t82 = 1.0./t81;
t83 = Tcf.*t3.*yi.*3.123341242976242;
t84 = t48+t83-TcN2.*t4.*t46.*3.123341242976242;
t85 = t82.*t84;
t86 = log(t85);
t87 = t49-1.0;
t88 = 1.0./t58;
g = [yi.*exp(-log(pj.*t2.*(t50+vl-Tcf.*t3.*yi.*6.4686515138e-1).*1.202723625380408e-1)+Tcf.*t2.*t3.*t76.*t79.*6.4686515138e-1+t2.*t47.*t52.*t58.*t86.*(t88.*(t21.*t34.*t87.*2.0+t3.*t9.*t20.*t49.*6.32182584656814e1)+Tcf.*t3.*t52.*6.4686515138e-1).*3.00680906345102e-2)-xi.*exp(-t61+Tcf.*t2.*t3.*t62.*t65.*6.4686515138e-1+t2.*t37.*t43.*t47.*t72.*(t74.*(t21.*t34.*t73.*2.0+t3.*t9.*t10.*t20.*6.32182584656814e1)+Tcf.*t3.*t37.*6.4686515138e-1).*3.00680906345102e-2);-t46.*exp(-log(pj.*t2.*(t50-t75+vl).*1.202723625380408e-1)+TcN2.*t2.*t4.*t76.*t79.*6.4686515138e-1-t2.*t47.*t52.*t58.*t86.*(t88.*(t21.*t34.*t49.*2.0+t4.*t22.*t32.*t87.*6.32182584656814e1)-TcN2.*t4.*t52.*6.4686515138e-1).*3.00680906345102e-2)+t5.*exp(-t61+TcN2.*t2.*t4.*t62.*t65.*6.4686515138e-1-t2.*t37.*t43.*t47.*t72.*(t74.*(t10.*t21.*t34.*2.0+t4.*t22.*t32.*t73.*6.32182584656814e1)-TcN2.*t4.*t37.*6.4686515138e-1).*3.00680906345102e-2)];

end

function [vv, vl] = findrealV(TcN2,Tcf,Ti,k,pcN2,pcf,pj,wN2,wf,xi,yi, fuel)

switch fuel
    
    case 'hexadecane'

   ind = 1;
    vl = v(TcN2,Tcf,Ti,k,pcN2,pcf,pj,wN2,wf,yi);
    vl = real(vl(ind));

    vv = v(TcN2,Tcf,Ti,k,pcN2,pcf,pj,wN2,wf,xi);
    vv = real(vv(ind));

    
    case 'dodecane'

    ind = 1;

    vl = v(TcN2,Tcf,Ti,k,pcN2,pcf,pj,wN2,wf,yi);
    vl = real(vl(ind));

    vv = v(TcN2,Tcf,Ti,k,pcN2,pcf,pj,wN2,wf,xi);
    vv = real(vv(ind));

    
    case 'butanol'
        
    vl = v(TcN2,Tcf,Ti,k,pcN2,pcf,pj,wN2,wf,yi);
    [m l] = min(real(vl));
    vl = real(vl(l));

    vv = v(TcN2,Tcf,Ti,k,pcN2,pcf,pj,wN2,wf,xi);
    [m l] = max(real(vv));
    vv = real(vv(l));

end
end